// <auto-generated />
using System;
using DataCleaner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataCleaner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DataCleanerDbContext))]
    [Migration("20260813112136_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("DataCleaner.Infrastructure.Persistence.CleaningRuleConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ImportProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportProfileId");

                    b.ToTable("CleaningRuleConfigurations");
                });

            modelBuilder.Entity("DataCleaner.Infrastructure.Persistence.ColumnMappingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImportProfileId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceColumn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetField")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportProfileId");

                    b.ToTable("ColumnMappings");
                });

            modelBuilder.Entity("DataCleaner.Infrastructure.Persistence.ImportJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvalidRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportJobs");
                });

            modelBuilder.Entity("DataCleaner.Infrastructure.Persistence.ImportProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CultureName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateFormat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberFormat")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ImportProfiles");
                });

            modelBuilder.Entity("DataCleaner.Infrastructure.Persistence.ImportResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DuplicatesRemoved")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ImportJobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModifiedRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputFileName")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidRows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId")
                        .IsUnique();

                    b.ToTable("ImportResults");
                });

            modelBuilder.Entity("DataCleaner.Infrastructure.Persistence.ValidationRuleConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImportProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportProfileId");

                    b.ToTable("ValidationRuleConfigurations");
                });

            modelBuilder.Entity("DataCleaner.Infrastructure.Persistence.CleaningRuleConfigurationEntity", b =>
                {
                    b.HasOne("DataCleaner.Infrastructure.Persistence.ImportProfileEntity", null)
                        .WithMany("CleaningRules")
                        .HasForeignKey("ImportProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataCleaner.Infrastructure.Persistence.ColumnMappingEntity", b =>
                {
                    b.HasOne("DataCleaner.Infrastructure.Persistence.ImportProfileEntity", null)
                        .WithMany("ColumnMappings")
                        .HasForeignKey("ImportProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataCleaner.Infrastructure.Persistence.ImportResultEntity", b =>
                {
                    b.HasOne("DataCleaner.Infrastructure.Persistence.ImportJobEntity", null)
                        .WithOne("Result")
                        .HasForeignKey("DataCleaner.Infrastructure.Persistence.ImportResultEntity", "ImportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataCleaner.Infrastructure.Persistence.ValidationRuleConfigurationEntity", b =>
                {
                    b.HasOne("DataCleaner.Infrastructure.Persistence.ImportProfileEntity", null)
                        .WithMany("ValidationRules")
                        .HasForeignKey("ImportProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataCleaner.Infrastructure.Persistence.ImportJobEntity", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("DataCleaner.Infrastructure.Persistence.ImportProfileEntity", b =>
                {
                    b.Navigation("CleaningRules");

                    b.Navigation("ColumnMappings");

                    b.Navigation("ValidationRules");
                });
#pragma warning restore 612, 618
        }
    }
}
